# Generated by Django 5.0.6 on 2024-05-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=20)),
            ],
        ),
    ]
