# Generated by Django 5.0.6 on 2024-05-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telephone',
            field=models.CharField(max_length=100),
        ),
    ]
